name: dardo
version: 0.0.1
description: A Pomodoro timer and recorder.
author: Ashley Richardson <ash@threeheadedmonkey.com>
homepage: https://github.com/ashri/dardo

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  redstone: '>=0.6.0 <0.7.0'
  shelf_static: '>=0.2.2 <0.3.0'
  path: '>=1.3.5 <1.4.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
